### ISSUE TITLE
Access the Webpage over Internet

### ISSUE THREAD

**Issue by David9696** [MoffKalast/vizanti#102]
Hi @MoffKalast ,

Thanks rot sharing this package.

By using ngrok or tailscale through forwarding, is it possible to access the web page with port of 5000 via Internet?

If yes, is it a need to forwarding the rosbrige port of 5001?

Thanks.

David

**Comment by MoffKalast** [comment]
Yeah that should work as long as the two ports are being forwarded, it's set up on 0.0.0.0 by default so it'll listen to any network interfaces you have. I've never tested with those two but it works with zerotier out of the box. Can't promise the throughput and latency will be any good though, that's mostly up to your use case.
