### ISSUE TITLE
the layout does not load the first time on the phone

### ISSUE THREAD

**Issue by DmitriySap** [MoffKalast/vizanti#117]
[Problem description]

It happens that after loading the application, when I go to the local ip address from my phone, not all the markup is loaded at once, but only the background, I have to reload the page, and often the reloading has to be done not once, but several times.

**Server Platform(s):**
 - OS: [e.g. Ubuntu 24.04]
 - Architecture: [e.g. x86_64]
 - ROS Version: [e.g. Jazzy]
 - Branch/Tag: [e.g. ros2]

**Client Platform(s):**
 - OS: [IOS]
 - Architecture: [e.g. aarch64]
 - Browser: [e. g. Safari]

**Comment by MoffKalast** [comment]
Hmm, I think I've seen something similar to that description before, but I've never been quite able to reproduce it consistently. Can you take some screenshots of how it looks when it doesn't fully load?

Also does it only happen on mobile or do you also see it on desktop?

**Comment by DmitriySap** [comment]
Hi, thanks for the reply!
On the computer I have not noticed this, but on phones, and on different phones, this happens very often, I attach a screenshot of what the application looks like on the phone when it is not loaded correctly
I mean, it just appears empty layout.
when reloading, the rest of the elements are loaded, but it may be necessary to reload repeatedly.
![image](https://github.com/user-attachments/assets/037bedf5-3ce6-4b5b-83ac-2559e329a9b6)

**Comment by MoffKalast** [comment]
Ok that's a familiar screen, it tends to happen when something inside [main.js](https://github.com/MoffKalast/vizanti/blob/acdaa3e6f2e952761b1d9555659555d925b42016/vizanti_server/public/js/main.js) crashes or it just doesn't get the list of available widget templates. Could be two things I think, either it's not actually getting the files and the promise somehow times out, or it's not actually calling the load function.

There's [this bit](https://github.com/MoffKalast/vizanti/blob/acdaa3e6f2e952761b1d9555659555d925b42016/vizanti_server/public/js/main.js#L130) that either immediately runs the template build (if all the html resources have loaded so it can actually attach the elements) or if the files haven't been loaded yet it waits for the DOMContentLoaded signal. It may be possible that webkit on iOS doesn't always send this signal or something. The docs do show it as fully supported though...

If it really is that, then we could potentially confirm by replacing that bit with something like this:

```js
setTimeout(() => {
    loadAll();
}, 6000);
```

Which would just wait for hopefully long enough and then attempt to build templates. If that always works then it's something to do with the load detection, if that's unreliable as well then it might have something to do with the file load in general. Or the browser blocking JS or something.

I can't seem to reproduce it on my end at the moment, so if you can check if there's any error outputs in the console on your phone with the web inspector it would be very helpful (although if it's just the load not executing there will be no errors).

**Comment by DmitriySap** [comment]
No, timeout doesn't work
I'll try the same thing on android later, and then I'll give you a definite answer, whether the problem is in ios only, or in mobile browsers in general.

**Comment by DmitriySap** [comment]
I don't have the ability to test on multiple android phones, but I've never had this bug on one. I can see the empty layout loading first and then the rest of the elements loading. I guess the problem is really an ios problem

**Comment by MoffKalast** [comment]
Yeah I've tested on two android devices and I'm not seeing it, but I don't have any Apple devices on hand to verify. If the timeout doesn't work then it might actually be related to loading the files themselves.

There was [this issue way back](https://github.com/MoffKalast/vizanti/issues/1) where Apple's ATS blocks requests over HTTP so all XHRs and fetches were turned into imports of serverside rendered JS files with the payload wrapped inside to get around it lol. I suppose it's possible they've made some changes to further restrict loading. If you check under Safari settings in iOS it might be possible to turn App Transport Security off to see if there's any improvement.

It's weird that it's so sporadic though, I'd expect ATS to either block 100% of the time or never.

**Comment by DmitriySap** [comment]
Okay, I'll check again, but somehow I don't think that's gonna help.
Anyway thanks for the replies, I appreciate it!
