### ISSUE TITLE
vizanti over virtual network

### ISSUE THREAD

**Issue by sualeh-rgt** [MoffKalast/vizanti#73]
This is an amazing work, bundle of thanks to the contributers.
Recently I faced an issue and I want to bring it to your attention.

Remote device is running a ros1 system in a virtual network and the intention is to monitor it remotely.

vizanti fails to get the tf data from the remote device and resultantly all tf related topics fail to get subscribed.

BUT

If the vizanti server is launched via ssh then all works fine.

**Comment by MoffKalast** [comment]
Thanks :smiley: I'm not sure I entirely understand your setup, but I think the VPN might be blocking port 5001 (the static serve is on 5000 which you seem to get, 5001 hosts rosbridge that would send over tf and other data). You can try adjusting ports [in the launch file](https://github.com/MoffKalast/vizanti/blob/d68fbbc21c2d43b103c19c710fe50d8ee0b6844f/launch/server.launch#L4) in case you can't unblock the default ones.

I'm not sure how launching it through ssh would make a difference though, to be clear we're comparing running vizanti on the robot in both cases, one launches manually/through systemd/etc. and the other gets launched from an ssh session? If so it might be some kind of permissions issue on the robot side.

**Comment by sualeh-rgt** [comment]
Thankyou for your response!
we tested again on a similar setup, and it worked without any issues.
Since the issue was related to tf only and not the connection itself, I suppose the function "clear_old_tfs" caused the problem.
I will further investigate and let you know.

**Comment by MoffKalast** [comment]
Hmm that could be possible, but what clear_old_tfs does is it removes any non-static tf frames that haven't been published for 15 seconds. If you have such frames, it would be best to move them over to /tf_static, otherwise rviz tends to treat them as missing too.

**Comment by MoffKalast** [comment]
@sualeh-rgt did you manage to find anything out?

**Comment by sualeh-rgt** [comment]
> @sualeh-rgt did you manage to find anything out?

Thankyou for asking! Did not happen again, and I did not explore it further.

**Comment by MoffKalast** [comment]
Ah alright, well let me know if you ever run into anything else and I'll close this one for now 😄
